apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: default
type: Opaque
stringData:
  # TODO: The secrets better stored in a secret manager like AWS Secrets Manager or GCP Secret Manager, even a self-hosted vault.
  DB_USER: "postgres"
  DB_HOST: "postgres-postgresql"
  DB_NAME: "mydb"
  DB_PASSWORD: "password"
  DB_PORT: "5432"

  
