image:
  repository: localhost:30500/flask
  tag: "0.1.0"

EnvFrom:
- secretRef:
    name: flask-secrets

volumeMounts:
  - name: flask-config
    mountPath: /app/config.yaml
    subPath: config.yaml

volumes:
- name: flask-config
  configMap: 
    name: flask-config
    items:
      - key: config.yaml
        path: config.yaml
