apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  template:
    spec:
      repository: davidh83110/self-service-db-acl-api

