name: Deploy

on:
  pull_request:
    branches:
      - main
      - testing
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.25.0'
    - name: Setup Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: v3.14.4
    - name: Helm upgrade
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        kubectl create namespace my-namespace
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig
        export KUBECONFIG=kubeconfig
        helm upgrade -i flask-app ./charts -f ./flask-app-values.yaml --set 'image.repository=localhost:30500/flask' --set 'image.tag=0.1.1'
