name: Deploy

on:
  pull_request:
    branches:
      - main
      - testing
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.25.0'
    - name: Setup Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: v3.14.4
    - name: Helm upgrade
      run: |
        # TODO: Change to fine-grained permission.
        helm upgrade -i flask-app ./deploy/charts -f ./deploy/flask-app-values.yaml --set 'image.repository=localhost:30500/flask' --set 'image.tag=0.1.1'
